### ISSUE TITLE
Does not work with cargo bench

### ISSUE THREAD

**Issue by velvia** [cbourjau/cargo-with#9] opened 2019-02-20 07:14 UTC
After installing and trying `cargo with "echo {bin}" -- bench`
```
Error: ErrorMessage { msg: "Unable to convert \'bench\' into a cargo subcommand" }

stack backtrace:
   0: failure::backtrace::internal::InternalBacktrace::new::h59b3db8423e4cf5e (0x10e71c9b8)
   1: <failure::backtrace::Backtrace as core::default::Default>::default::ha057354baab460c1 (0x10e71cc64)
   2: cargo_with::cargo::Cmd::from_strs::h41a41d93068aa265 (0x10e7123cd)
   3: cargo_with::runner::runner::h426b4b78cc407ce9 (0x10e717517)
   4: cargo_with::main::h57a9494064ed692b (0x10e70d932)
   5: std::rt::lang_start::{{closure}}::h6a72812a9432124a (0x10e71663a)
   6: std::panicking::try::do_call::hb3270f6ae846849d (0x10e80f837)
   7: ___rust_maybe_catch_panic (0x10e8215be)
   8: std::rt::lang_start_internal::ha07e743882e341f3 (0x10e8101ca)
   9: _main (0x10e70daf8)
```

**Comment by barskern** [comment] 2019-02-20 11:09
This is by design as we only currently support `cargo run` and `cargo test`. However it could be extended to also work with `cargo bench`.

**Comment by cbourjau** [comment] 2019-02-20 20:41
Thanks a lot for pointing this out @velvia! `bench` should really be supported as well. It is only a question of fishing out the right build artifact from cargo's output which is messier than it sounds. I am actually just setting up a few minimal example projects and one of them will have benchmarks. So that should be a good starting point if you would like to take a swing at it?

**Comment by cbourjau** [comment] 2019-02-20 22:27
This might have been easier than anticipated and should be fixed with PR #12

**Closed as completed** 2019-03-06 16:59 UTC

**Comment by velvia** [comment] 2019-03-12 00:42
Say, as end users is there any easy way to install the update, or do we have to wait until you release a new version?   Crates.io <http://crates.io/> still lists 0.2.0 as latest release.

**Comment by barskern** [comment] 2019-03-12 01:44
You could clone the project and run `cargo install --path .` in the root of the project.
